### ISSUE TITLE
Use on multiple sets of tabs

### ISSUE THREAD

**Issue by jraeruhl** [jellekralt/Responsive-Tabs#100]
Is there a way to use responsive-tabs on multiple sets of tabs? I am testing it out currently and it's taking all of the tabs from both tab groups and combining them into one set of responsive tabs.

**Comment by jellekralt** [comment]
I don't think I understand exactly what you are trying to accomplish. Do you want to have multiple instances of tabs? If so, please check if your tab ID's are unique.
