### ISSUE TITLE
Using effects with the panel

### ISSUE THREAD

**Issue by inputproductions** [jellekralt/Responsive-Tabs#101]
I noticed when specifying effects (ie "fade"), the effects are applied to the entire panel itself. This poses a problem when the panel is styled with a border.

Is there any way to apply the effects on the panel's children so that only the panel _contents_ fade and not the panel itself?

**Comment by jellekralt** [comment]
Unfortunately, it isn't possible to apply the effect to the children of the panel. I don't know if this is an option in your particular use case, but you could consider putting styles like the border on the container element itself, instead of the tab panel itself.
