### ISSUE TITLE
Equal panel heights when in tabs view

### ISSUE THREAD

**Issue by coxrichuk** [jellekralt/Responsive-Tabs#102]
I need the ability to match / equalise the panel heights when in tabs view.

My thoughts are to have have an option of `fluidHeight` and have this set to `true` by default for backwards compatibility?

I have a PR ready if you are happy for this to go in ...

**Comment by t3premium** [comment]
An option for collapsible would be great.
https://jqueryui.com/tabs/#collapsible

**Comment by jellekralt** [comment]
The fluidHeight option is now available.

@t3premium, the collapsible option has already been available for quite some time.
