### ISSUE TITLE
Callback on click (not activate/deactivate)

### ISSUE THREAD

**Issue by Dobby89** [jellekralt/Responsive-Tabs#108]
Is there a way to have a callback for when a tab is clicked (regardless of whether it's activated or deactivated)?

The activated callback is only run once when the tab becomes active

My requirements are that I need to know when a tab is clicked every time. The tab could be active or not-active, but I just need a callback.

In my implementation, one of the tabs activates a modal popup, but currently it only allows me to know its been clicked if it's being activated. I need to know it's been clicked even when the tab is already open.

**Comment by jellekralt** [comment]
There is no way out of the box to achieve this. I'm afraid the only way to do this is adding click handlers on the tabs yourself.

**Comment by Dobby89** [comment]
I made a [pull request](https://github.com/jellekralt/Responsive-Tabs/pull/109) for this if anyone else wants something similar.
