### ISSUE TITLE
refresh tabs

### ISSUE THREAD

**Issue by TripleMap** [jellekralt/Responsive-Tabs#116]
What is the better way to reload tabs?
I'm use it with knockout.js, and after reloading viewModel with method forEach it is looks like element did not use plugin, but style is partically uses. And also, if my view reload ul/li element, that not dynamical updating they are work great.
![default](https://cloud.githubusercontent.com/assets/22080514/19764391/6de23938-9c4b-11e6-8188-ae81bf9a23f6.png)
Thank you.

**Comment by jellekralt** [comment]
Unfortunately, this is not possible at the moment
