### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by llsousa** [jellekralt/Responsive-Tabs#121]
Just to inform that the link [http://jellekralt.github.io/Responsive-Tabs/](http://jellekralt.github.io/Responsive-Tabs/) is returning a 404 (page not found).

**Comment by jellekralt** [comment]
Seems to be a GitHub pages issue: https://twitter.com/githubstatus/status/801079562893299712

**Comment by jellekralt** [comment]
Should be solved now https://twitter.com/githubstatus/status/801121500044595200
