### ISSUE TITLE
Adding of undefined in URL on IE10

### ISSUE THREAD

**Issue by svdg** [jellekralt/Responsive-Tabs#124]
I discovered that instead of #tab- 'undefined' is added to the url in IE10 on Win 8. This is also the case in your demo. Any idea how to solve this?

**Comment by jellekralt** [comment]
Good find! Turns out IE10 on Win8 doesnt have `window.location.origin` available, I'll see if I can fix this quickly

**Comment by jellekralt** [comment]
This is now fixed in the latest version
