### ISSUE TITLE
Click callback: is it possible to avoid navigating away at this point?

### ISSUE THREAD

**Issue by chimos** [jellekralt/Responsive-Tabs#126]
Hi, 
with Responsive-Tabs, when the user clicks on another tab, and there are unsaved changes, I need to show a confirm box similar to "You could loose changes... are you sure? Ok + Cancel". 
The problem is that I don't know how to stop the loading / activation of the new tab, when the user choses to cancel (and stay in the current tab).

I tried with `return false;` without success:

```javascript
            $('#horizontalTab').responsiveTabs({
                rotate: false,
                startCollapsed: 'accordion',
                collapsible: 'accordion',
                setHash: false,
                active: '".$tab_idx."',
                disabled: '".$tabs_disabled."',
                click: function(event, tab) {
                    if ( $('#horizontalTab').hasClass('unsaved_state') ) {
                        var result = confirm('You could loos changes.. Are you sure?');
                        if (!result) {
                            return false;
                        }
                    }
                }
            });
```

I couldn't find any info about this in docs or examples. Any help would be appreciated. 
Thank you!

**Comment by jellekralt** [comment]
This is not something that is currently supported. I would be open to a solution with something live event.preventDefault(), but that would be something for the future.

**Comment by chimos** [comment]
Ok, thanks for your answer. I ended up modifying de original .js file in a not nice/clean way, in order to get it working ASAP. So, you can consider this issue closed for me. 
Thanks again
