### ISSUE TITLE
Flash of Unstyled Content (FOUC) on Tabs

### ISSUE THREAD

**Issue by neilgee** [jellekralt/Responsive-Tabs#130]
Am getting a flash of unstyled content (fouc) on the list items on the main list nav any pointers on getting around this. - Example - http://saltuary.com.au/prices/

**Comment by jellekralt** [comment]
There is no 'built-in' solution to prevent this. The classes are put on the tabs with javascript, so if there is any (heavy) js running before the responsive tabs js, you can indeed have FOUC. You could solve it by initially hiding the tabs by adding a class, and after loading, removing that class.

**Comment by neilgee** [comment]
cool thanks...

CSS
```
.hidetabs  {
	display: none;
}
```
JS
```
jQuery(function( $ ){
	 $('#tabs1').removeClass('hidetabs');

         $('#tabs1').responsiveTabs({
         startCollapsed: 'accordion',
         // Add other parameters
         });
});
```
