### ISSUE TITLE
Change class depending on accordion / tabs mode

### ISSUE THREAD

**Issue by Alex360hd** [jellekralt/Responsive-Tabs#134]
Hello,

For better styling, I would like to add classes to the parent element depending on the mode of the tabs (tabs or accordion).

I saw that "activateState" callback function, but I don't know how to detect if we are in accordion or tab mode in order to give the correct class to my element.

Could you please point me the right direction ?

Thanks

Alex

**Comment by coxrichuk** [comment]
You need to bind the `getState` into a window resize:

```javascript
var $tabs = $('.foo-tabs').responsiveTabs();
$(window).resize(function(){
     console.log($tabs.responsiveTabs('getState')); // returns tabs || accordion
});
```

It's a shame there isn't an event fired off when there is a change in state

**Comment by jellekralt** [comment]
Thanks @coxrichuk
