### ISSUE TITLE
Default Behaviour

### ISSUE THREAD

**Issue by IanMustard** [jellekralt/Responsive-Tabs#140]
Just a question...

Why does the demo default behaviour actually not follow what you actually want or expect it to do?

When I click a tab I want the tab content to reveal, not show in a separate box the fact the tab has been clicked.  Now I am sure this is all very clever and that but what I and my users want is that when they click a tab they can see the content in the tab and not be told what they have clicked.  

This seems utterly, utterly stupid.

I am not a programmer but I want to use this type of element without having to pick it apart just to get the default expected behaviour of something to work.  Consequently I am now having to look elsewhere for something I can actually use...

**Comment by jellekralt** [comment]
I'm sorry, but to me it sounds very weird to state that there is one behaviour "you actually want or expect it to do". Maybe you expect it do be very basic, but someone else might want to see a demo of some of the more advanced features. 

I'm not sure what you mean with your users wanting to see the content in the tab. The demo does exactly that, and additionaly there are some extra features in there. The fact that you are not able to just use the stuff you need, and ignore the rest is in no way a good reason to make the demo more simple.

Maybe the fact that you are not a developer explains your rude attitude. In case you don't know, the software you are complaining about has been developed by people for other people to use, free of charge. If you want to get software customized to your specific needs, hire a developer (and be ready to pay up). If you're hoping to get some actual help with integrating open source software, the first step would be to stop being rude and just ask for help. I honestly really don't care you have to look something else to use, like I said, I'm spending my free time on this, and i'm not getting a dime out of it.

**Comment by IanMustard** [comment]
You're right of course, I apologise.

Just that when I think of tabs, I expect to click on a tab and it show that content, just the demo doesn't do that and I appreciate this is more complicated than that and perhaps I expect you want to show off your skills whereas I just need something simple.  Apologies again and kudos to you and your project.

**Comment by jellekralt** [comment]
Thank you for your apologies. The reason that the demo is complicated is not to show of my skills, but to provide an example to everyone who wants to implement the plugin. The demo should should show the content for the tab however, so if that doesn't work for you there might be another issue. When I run the demo, it does show the content. How are you running the demo, and in which browser?

**Comment by IanMustard** [comment]
I am running the demo locally from a downloaded clone on a late 2015 imac OSX 10.11.6 in firefox 55.0.2

I do think I have another solution for my particular instance so though I appreciate you looking into this but its not a priority for me, so in your own time :P
