### ISSUE TITLE
Styling accordion tabs individually

### ISSUE THREAD

**Issue by terryupton** [jellekralt/Responsive-Tabs#144]
Please correct me if I am mistaken, but I cannot see a way to style the accordion tabs individually. I have a series of tabs that each need a different colour. This is easily achieved on the desktop version, as it can be added to the markup. However, the accordion markup is fixed and JS drive. So can't manipulate in the HTML. Is there a way to be able to add individually classes to each accordion title?

`class="r-tabs-accordion-title r-tabs-state-active"`

**Comment by jellekralt** [comment]
There is indeed no way to individually style the tabs, and there is no planned feature to enable this. You could solve this with something like `nth-child` in CSS, or by adding classes manually with javascript.

**Comment by terryupton** [comment]
Any tips on how to add classes manually with javascript?
