### ISSUE TITLE
FOUC on tabs with a lot of content

### ISSUE THREAD

**Issue by RobbieLensen** [jellekralt/Responsive-Tabs#145]
Hi there,

I have noticed that when you have a large number of tabs with a lot of content in them the page has a Flash Of Unstyled Content (FOUC) because the plug-in just takes a bit of time before styling all the content.

Would there be a way to detect when the plugin has finished loading (maybe a promise return?) so it can be hidden until all styles are applied?

**Comment by jellekralt** [comment]
You could use the `load()` option for this: https://github.com/jellekralt/Responsive-Tabs#load

**Comment by RobbieLensen** [comment]
That did the trick indeed, good stuff!

Thanks again!
