### ISSUE TITLE
Do not make assumptions on the markup.

### ISSUE THREAD

**Issue by neojp** [jellekralt/Responsive-Tabs#15]
We were building a tabset with your script and noticed that your code makes assumptions on the code.

One of our developers wrote the tab panels as `<li>`s inside a `<ul>`, which worked fine until he added an `<a>` tag inside the content.

The following function `ResponsiveTabs.prototype._loadElements` on [line 140](https://github.com/jellekralt/Responsive-Tabs/blob/master/js/jquery.responsiveTabs.js#L140) assumes that the navigation will always be a `<ul>` and the content won't. Therefore breaking the script when the markup isn't what you expect.

Ideally, if you have an option to specify the navigation element you can avoid this scenario.

**Comment by merauluka** [comment]
I agree that it would be great to add a little flexibility on the tabs. Just today I was implementing this on a client's site using content generated by the CMS. The `<ul>` element was wrapped in a div, which broke Responsive Tabs entirely. I had to write a preprocess to remove the wrapper to get this working.

Now that it is working, I must admit it's pretty slick! Great idea on this plugin and thanks very much for posting it.

**Comment by jellekralt** [comment]
Thanks to @falconwhite you can now at least pick a custom container for the naviation element. In the foreseeable future, I'm not expecting that i'm going to have time to do more work on this, so for now this should be enough.
