### ISSUE TITLE
Add new tab followed by $('.toBeTabbedClass').refresh() fails

### ISSUE THREAD

**Issue by ashvant** [jellekralt/Responsive-Tabs#23]
When dynamically adding a new tab via ajax (done by adding a new <li> and <div> entries in the appropriate place) and followed by $('.toBeTabbedClass').refresh() fails to add the new tab. The result is un-styled <li> and <div> data following the current <li> and <div> data's respectively.

**Comment by jellekralt** [comment]
Closing this in favor of #11
