### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by torkiljohnsen** [jellekralt/Responsive-Tabs#27]
The tabs don't have a tabindex and can't be accessed by keyboard.

This is easily fixed by adding `tabindex="0"` to the clickable elements (li items and h2 for accordion), and adding something like this to the js:

```
$currentTab.keypress(function (e) {
    if (e.keyCode == 13 || e.keyCode == 32) { // Detect enter or spacebar
        $currentTab.click();
    }
});
```

**Comment by jellekralt** [comment]
The tabs should be accessible by keyboard now. As the tabs are HTML links, it should work just fine.
