### ISSUE TITLE
Option to not generate markup

### ISSUE THREAD

**Issue by dimaip** [jellekralt/Responsive-Tabs#32]
I would like to have an option to disable automatic insertion of classes an accordion title blocks, and rather write final markup myself. I'm using this tabs in TYPO3 Neos and the markup transformations cause a lot of problems.
What worked for me was just to change lines 171-2 to:
```
$accordionTab = $panel.prev();
$accordionAnchor = $accordionTab.children();
```
I understand it may not be interesting for you, so it's OK if you just ignore it :)

**Comment by jellekralt** [comment]
It is now possible to change the markup for the accordion title blocks (since [v1.5.0](https://github.com/jellekralt/Responsive-Tabs/releases/tag/v1.5.0)).
