### ISSUE TITLE
The "active" initialization option is ignored when rendering in mobile breakpoint

### ISSUE THREAD

**Issue by dkemper01** [jellekralt/Responsive-Tabs#33]
The json object passed to the responsiveTabs method, used to initialize and render the responsive tab control, contains an "active" option.  This option will open the active tab upon successful initialization in the desktop breakpoint of this control, but not for the mobile (tablet and phone) breakpoint; 

@media only screen and (max-width: 768px) { ... }.  

So, in short, active works for desktop but not for mobile.

**Comment by oilvier** [comment]
Hi,

I know this is an old issue, but I'm in the case where I want to use the `load` function with the option `startCollapsed` set to 'accordion' and it's not working when in accordion mode.

[Here's a demo](https://jsfiddle.net/y6euyowq/)
