### ISSUE TITLE
Not possible to create Nested Tabs- styles are getting messed up

### ISSUE THREAD

**Issue by surenazatyan** [jellekralt/Responsive-Tabs#35]
Hi its pity but its not possible to set nested tabs.
The tabs styles mess up on a tab where I created nested tabs.

**Comment by jellekralt** [comment]
Hi there,
In what way do the styles mess up? I've tested it out and nested tabs work fine for me. There are some things to take into consideration though:
* You should always change the ```id```'s of the tab panels for each to be unique
* If you put the nested tab in a parent tab that is visible on initial load everything should work
* However, if you nest a tab in a hidden parent panel, the css of the nested tab won't render everything correctly. This is the way rendering works in ```display: none``` elements, unfortunately I can't do anything about this. As of yet there is no 'refresh' method available which reloads the styling. However, you could force open the tab you want open on the nested tab with the ```activate``` method.
