### ISSUE TITLE
Reload a tab on clicked.

### ISSUE THREAD

**Issue by mikezclements** [jellekralt/Responsive-Tabs#41]
I'm so very thankful that you made this amazing plugin but may I asked a question. I'm trying to add some codes to enable the tabs to reload once clicked. I add this line of code

activate: function(clicked) { 
location.reload(false);
}

unfortunately once I run the code the page keeps on reloading again and again. Hope you can help me. Thank you.

**Comment by jellekralt** [comment]
Hi,
I'm glad you like the plugin :).
The page keeps reloading because the activate function runs on first load, because when loaded, the first tab is opened. If you want this to work you could add a check so that when the activate function is run for the first time, the location.reload doesn't run.

**Comment by mikezclements** [comment]
Good day,

Finally solve this, I fix it by adding onClick="window.location.reload() attribute on link of tab title.  

Thank you.
