### ISSUE TITLE
Disable moving up of page when tab is clicked

### ISSUE THREAD

**Issue by kitchary** [jellekralt/Responsive-Tabs#42]
Im wondering if there is a way to remove the moving of page when Im switching tabs like it stay on position and will not move when I change tab. 

By the way, this indeed a great plugin :)

Thank you.

**Comment by jellekralt** [comment]
Hi,
Do you have this issue in a specific browser? I can't seem to reproduces this issue.

**Comment by jellekralt** [comment]
I'm closing as this didn't get any follow up answers.
@kitchary you're welcome to re-open if you have more info.
