### ISSUE TITLE
Chrome page refresh

### ISSUE THREAD

**Issue by coxrichuk** [jellekralt/Responsive-Tabs#45]
Chrome has a bug when `window.location.hash` is updated it does a complete page repaint/refresh of  and so looks like the page is jumping when clicking between tabs.

See - http://stackoverflow.com/questions/5657083/window-location-hash-refresh-in-chrome

To stop this could we look at implementing `history.pushState` for supported browsers and then falling back to `windown.location.hash` for older browsers?

Let me know if you want this as a pull request?

I do love Responsive Tabs, but at the moment this is a bit of a blocker for me.

**Comment by jellekralt** [comment]
Thanks for the pull request!
