### ISSUE TITLE
Is it possible to use jquery.cookie to remember the tab?

### ISSUE THREAD

**Issue by anthonysbrown** [jellekralt/Responsive-Tabs#48]
Hello, I was wondering if its possible to have jquery.cookie remember which tab was selected.

**Comment by jellekralt** [comment]
Hi there, you could use the [Activate state](https://github.com/jellekralt/Responsive-Tabs#activate-state) method to listen for the selection of a tab and save it to a cookie. When you are loading the page for the first time you could use the [active tab options](https://github.com/jellekralt/Responsive-Tabs#active-tab) to select the initial tab from the cookie.

**Comment by anthonysbrown** [comment]
Thanks!
