### ISSUE TITLE
link from Global navigation

### ISSUE THREAD

**Issue by Akintosh** [jellekralt/Responsive-Tabs#49]
HI!
I'm so very thankful that you made this wonderful plugin.
This help me a lots!
But I have a question,when click a Global navigation/(following example: '.slide1 li a')  which link to each tab,
Current demo link to each tab top,but I want to adjust to link to screen top with opening target tabs.
('cause have space between screen top and tab top.)

I tried to onClick="window.scroll function but seems didn't work,
how can I change link to screen top instead of tab top?

  <ul class="Gnav">
    <ul class="slide1">
    <li><a href="index.html#tab-1">link to #tab-1</a></li>
    <li><a href="index.html#tab-2">link to #tab-2</a></li>
    <li><a href="index.html#tab-3">link to #tab-3</li>
    </ul>

**Comment by jellekralt** [comment]
I'm sorry but I don't fully understand what you are trying to achieve or what is causing problems. Is it the fact that you want the page to jump to the absolute top instead of the tab elements?

**Comment by Wishmaker888** [comment]
HI,
Your plugin is cool. But I also try to activate needed for me tab by clicking on a separate button.
I wish, when I click on button in sidebar - to activate second tab and scroll to it. Scrolling I've created - it is not a problem, but an activation of tab - it is problem. Any solutions?

**Comment by jellekralt** [comment]
@Wishmaker888 You can use the [activate](https://github.com/jellekralt/Responsive-Tabs#activate-1) method for this.

**Comment by jellekralt** [comment]
Closing this for now
