### ISSUE TITLE
Is it possible to show all panels on mobile?

### ISSUE THREAD

**Issue by gabrudan** [jellekralt/Responsive-Tabs#5]
I really like how the script works but I have a particular situation where the content is getting pretty long and while I like having tabs on desktop I would prefer to have all panels expanded on mobile  to avoid a lot of scrolling up and down. Is this posible?

Thanks,
Gabriela

**Comment by srikat** [comment]
It's actually

``.r-tabs .r-tabs-panel {
	display: block;
}`
