### ISSUE TITLE
r-tabs-accordion-title choose what type html element / tag this should be

### ISSUE THREAD

**Issue by coxrichuk** [jellekralt/Responsive-Tabs#51]
Would it be possible to set what type of html element / tag `.r-tabs-accordion-title` is applied to.

Ideally I need to specify that this could be a h2, h3 or span

I am more than happy to put in a pull request for this ...

The default would be just a `<div>` for backwards compatibility purposes

I am thinking a setting called `accordionTitleElement`

**Comment by jellekralt** [comment]
I'd be happy to accept this feature as a pull request :)
