### ISSUE TITLE
Slide animation improvement

### ISSUE THREAD

**Issue by entozoon** [jellekralt/Responsive-Tabs#54]
I wondered if it were possible to change the slide animation, so that when opening a new tab.. the current tab slides up, then after that, the new one slides down. Which I think makes more sense visually.

I did a little fork https://github.com/entozoon/Responsive-Tabs

Which gives it extra options (only affecting animated transitions, separately for accordion or tab mode) to be used like this:
```
$('.responsivetabs').responsiveTabs({
	animation: 'slide',
	patientAnimationTabs: true,
	patientAnimationAccordion: false,
});
```

Feel free to merge the change into yours if you like.

**Comment by jellekralt** [comment]
Thanks for your suggestion! I've added your functionality in the latest release of the plugin. I've changed up the code a little bit to be more in sync with the rest of the plugin's code.
