### ISSUE TITLE
How to add more than one horizontal tab panels?

### ISSUE THREAD

**Issue by hbkarun** [jellekralt/Responsive-Tabs#59]
Hello,
I have been using this tab plugin,i completed inserting succesfully one complete horizontal tab,
BUt the problem is i want another horizontal tab in the same page,how to achieve this,???
![afa](https://cloud.githubusercontent.com/assets/1058779/7488685/4163b5ee-f3eb-11e4-8f98-caab0630b6fb.PNG)

**Comment by jellekralt** [comment]
Hi,
You can easily add another tab by either adding another element with the same selector you've used for the first one:
```javascript
$('.my-tabs').responsiveTabs();
```
```html
<div class="my-tabs">...</div>
<div class="my-tabs">...</div>
```
Or create another instance by setting a new selector for the second tabs:
```javascript
$('.my-tabs1').responsiveTabs({});
$('.my-tabs2').responsiveTabs({});
```
```html
<div class="my-tabs1">...</div>
<div class="my-tabs2">...</div>
```

Hope this helps!
