### ISSUE TITLE
After resize tabs can be completely closed?!

### ISSUE THREAD

**Issue by godsdog** [jellekralt/Responsive-Tabs#65]
Hello, I use the plugin with: responsiveTabs({collapsible: "tabs"});

So I only want tabs and no accordion. After resizing the browser it is always possible to completely close all tabs by clicking on the active tabs navigation item. No content anymore for the user, only navigation is visible.

Is there any chance to disable that?

**Comment by jellekralt** [comment]
Hi there,

If I understand correctly you would like to programmatically close all the tabs, right? You could loop the number of tabs and close them with the ```deactivate``` method: https://github.com/jellekralt/Responsive-Tabs#deactivate-1

**Comment by godsdog** [comment]
No that's not the point. The issue is that after resizing the browser, it is possible to close the tabs so that no content is visible. This is confusing for the visitor. I want to disable that, so that there is always content visible. I think its a bug, because this issue only appears after resizing.

**Comment by jellekralt** [comment]
Ok, so what your are saying is that you don't want the tabs to be closable? The tabs close because you configured it with ```{collapsible: "tabs"}```. This option enables the closing of a tab. However, this should work even before resizing. In which browser does this only happen after resizing?

**Comment by godsdog** [comment]
Sorry! My fault. I have to use responsiveTabs({collapsible: false}); Now it's working like i am expecting it. Thangs a lot!

**Comment by jellekralt** [comment]
No worries, good to hear it works now!
