### ISSUE TITLE
IE shows all accordion content, firefox and chrome don't

### ISSUE THREAD

**Issue by peggythrasher** [jellekralt/Responsive-Tabs#67]
I took this project over from someone else, so I may be overlooking something simple.  I have 5 tabs, each with a search bar in the content.  When I display in Firefox and Chrome I only see one search bar (whichever tab is selected).  In both IE11 and IE8 I see all of the search bars.  How can I make IE behave?

Thanks

**Comment by jellekralt** [comment]
Hi there, 
I don't know what might be causing this, but I honestly doubt that this has something to do with the plugin. If you are still having this issue, please supply a link to your site (or a jsbin/jsfiddle/etc) with an example.

**Comment by peggythrasher** [comment]
The problem is only occurring on IE8, so it is probably not worth fixing.

Thanks for your response!

Peggy

**Comment by jellekralt** [comment]
I've tried reproducing it on IE8 by adding text fields to the tab contents, but everything looks fine. It definitely worth fixing on IE8 if something is really broken :) so if you have more information (a piece of example code would be even better), let me know!

**Comment by peggythrasher** [comment]
See library.dover.nh.gov  (the top search bar)

Thanks!

Code is:
<link type="text/css" rel="stylesheet" media="screen" href="/web_resources/themes/dept-library/css/dpl_responsive_tabs.css">
<link type="text/css" rel="stylesheet" media="screen" href="/web_resources/themes/dept-library/css/dpl_responsive_tabs_style.css">
                <div id="search_tabs">
                <ul>
                                <li><a href="#tab-01">Library Catalog</a></li>
                                <li><a href="#tab-02">Library Web Site</a></li>
                                <li><a href="#tab-03">Overdrive Downloads</a></li>
                    <li><a href="#tab-04">Hoopla Downloads</a></li>
                                <li><a href="#tab-05">Magazines &amp; Articles</a></li>
                </ul>

                <div class="tab_content" id="tab-01">
                                <form action="http://librarycatalog.dover.nh.gov/cgi-bin/koha/opac-search.pl?idx" method="get">
                                 <input class="hsinput" name="q" placeholder="Search Library Catalog" type="text" value="Search Library Catalog" onFocus="this.value=''">
                         <input class="hsbutton" type="submit" name="submit" value="submit">
                                </form>
                </div>

                <div class="tab_content" id="tab-02">

  <form action="/government/city-operations/library/search-results.html" method="get" >
<input name="cx" type="hidden" value="000115712370344491370:y1vdwpwabcm" />
<input name="ie" type="hidden" value="UTF-8" />
<input class="hsinput" id="q"  name="q" placeholder="Search Library Site" type="text" value="Search Library Site" onFocus="this.value=''">
<input class="hsbutton" type="submit" name="submit" value="submit">
  </form>
</div>


                <div class="tab_content" id="tab-03">
                                <form action="http://nh.lib.overdrive.com/BANGSearch.dll?Type=FullText&amp;URL=SearchResults.htm&amp;PerPage=20" method="post" target="_blank">
                                                <input name="FullTextField" type="hidden" value="All">
                                                <input class="hsinput" name="FullTextCriteria" placeholder="Search Audiobooks, eBooks and Magazines" type="text" value="Search Audiobooks, eBooks and Magazines" onFocus="this.value=''">
                                                <input class="hsbutton" type="submit" name="submit" value="submit">
                                </form>
              </div>

              <div class="tab_content" id="tab-04">
                                <form action="https://www.hoopladigital.com/search?" method="post" target="_blank">
                                                <input name="FullTextField" type="hidden" value="All">
                                                <input class="hsinput" name="q" placeholder="Search Music, Movies, TV Shows, Audiobooks, eBooks and Comics" type="text" value="Search Music, Movies, TV Shows, Audiobooks, eBooks and Comics" onFocus="this.value=''">
                                                <input class="hsbutton" type="submit" name="submit" value="submit">
                                </form>
              </div>
              <div class="tab_content" id="tab-05">
                <script src="http://support.ebscohost.com/eit/scripts/ebscohostsearch.js" type="text/javascript"></script>
                <div id="header-search-bottom-form-magazines-articles">
               <form action="" id="ebscohostCustomSearchBox" method="post" name="ebscohostCustomSearchBox" onsubmit="return ebscoHostSearchGo(this);">
                                <input id="ebscohostwindow" name="ebscohostwindow" type="hidden" value="1">
                                <input id="ebscohosturl" name="ebscohosturl" type="hidden" value="http://search.ebscohost.com/login.aspx?direct=true&site=ehost-live&scope=site&type=1&db=f5h&mode=and&lang=en">
                                <input id="ebscohostsearchsrc" name="ebscohostsearchsrc" type="hidden" value="url">
                                <input id="ebscohostsearchmode" name="ebscohostsearchmode" type="hidden" value="+AND+">
                                <input id="ebscohostkeywords" name="ebscohostkeywords" type="hidden" value="">
                                <input class="hsinput" id="ebscohostsearchtext" name="ebscohostsearchtext" placeholder="Search Magazines and Articles" value="Search Magazines and Articles" onFocus="this.value=''" type="text">
                                <input class="hsbutton" type="submit" name="submit" value="submit">
                                
                                                                <div class="limiter" style="display:none;">
                                                                                <input id="chkFullText" name="chkFullText" type="checkbox">
                                                                                <label for="chkFullText">Full Text</label>
                                                                </div>
                                                <div class="limiter" style="display:none;">
                                                                <input id="chkReferencesAvailable" name="chkReferencesAvailable" type="checkbox">
                                                                <label for="chkReferencesAvailable">References Available</label>
                                                </div>
                                                <div class="limiter" style="display:none;">
                                                                <input id="chkPeerReviewed" name="chkPeerReviewed" type="checkbox">
                                                                <label for="chkPeerReviewed">Peer Reviewed</label>
                                                </div>
                    </form>
                  </div>
                </div>
              </div>

    

<script src=
"/web_resources/themes/dept-library/js/dpl_jquery_responsiveTabs.js" type=
"text/javascript"></script> <script type="text/javascript">
$(document).ready(function () { $('#search_tabs').responsiveTabs({ rotate: false, startCollapsed: 'accordion', collapsible: 'accordion', setHash: true, }); });
</script>

**Comment by jellekralt** [comment]
Thanks for the example! I've tested the site on IE8 (both on XP and Win7) and as far as i can tell, I don't see all the tab contents, but only the content of the selected tab. Do you maybe have more info for me?

**Comment by peggythrasher** [comment]
I just tried it on an XP machine (so it is IE8) and the tabs worked OK, but there were other funky formatting things (I love IE!!).

It shows up funny on my Win7 machine when I use Compatibility mode (see screen shot).  A co-worker also saw it on her computer in compatibility mode.

I’m on version 11.0.9600.17959, update version 11.0.22

What else can I tell you?

**Comment by jellekralt** [comment]
Unfortunately, compatibility mode is not that reliable :worried:. If this only happens in compatibility mode, I don't think it is worth investigating/debugging any further. Thanks for the information though!

**Comment by peggythrasher** [comment]
Sounds good to me.  Thanks for looking at it.
