### ISSUE TITLE
Google maps is not rendered

### ISSUE THREAD

**Issue by banifou** [jellekralt/Responsive-Tabs#68]
I use Google maps in a secondary tab (not default active one). When I click this tab the map is not rendered, I mean the frame is there but all grey. The map get rendered only after reloading the page. Why? How can I fix it?

Thanks

**Comment by coxrichuk** [comment]
@banifou Google maps is unable to draw a map if its inside a hidden div

Best way around this I have found in the past is to only draw the map once the tab has been loaded.

**Comment by banifou** [comment]
Sorry, but I'm not using it any more. Your response comes far too late!!!
By the way, I tried everything... It's not working

**Comment by jellekralt** [comment]
For future reference, for anybody that runs into this problem: @banifou is right, this problem is not specific to this plugin, but is due to Google Maps not being able to draw inside a ```display: none``` element. For more info, check: http://stackoverflow.com/questions/4700594/google-maps-displaynone-problem
