### ISSUE TITLE
Multiple Tabs Open

### ISSUE THREAD

**Issue by coxrichuk** [jellekralt/Responsive-Tabs#71]
Is there a way when in Accordion mode to have multiple tabs / panels open on first load?

If this isn't available I am happy to put a pull request into facilitate this.

I guess the best way would be to pass an array to `active` similar to `disabled` ?

**Comment by jellekralt** [comment]
Currently, this is not supported. I'd be happy to accept a pull request though! Off the top of my head I think the ```_getStartTab``` function would need some work and the places where the function is called.

**Comment by jellekralt** [comment]
Also, this relates to #40

**Comment by jellekralt** [comment]
Closing this as a duplicate of #40
