### ISSUE TITLE
Active state on filtered items

### ISSUE THREAD

**Issue by terrybarth** [jellekralt/Responsive-Tabs#74]
Is there a way to put an active class on the list item that is clicked showing a filtered list? I'd like to style the item selected by the user.

Thanks!

**Comment by jellekralt** [comment]
Hi there,
I don't fully understand what you mean with list items or filtered list. Do you mean one of the tabs, or accordion tabs?

**Comment by terrybarth** [comment]
How embarrassing. (forehead slap) I posted this on the wrong project. My apologies.

**Comment by jellekralt** [comment]
No worries :), I thought that might be it.
