### ISSUE TITLE
Start with an accordion option?

### ISSUE THREAD

**Issue by djmtype** [jellekralt/Responsive-Tabs#76]
Without adding excess CSS to create a workaround, is there a way to start with an accordion if the view is greater than 768px?

**Comment by jellekralt** [comment]
The accordion is only shown based on media queries. There is no way to start with an accordion without changing the CSS. Do you only want to show the accordion, or do you want to show the tabs after changing the browser size?

**Comment by jellekralt** [comment]
Closing this due to lack of a reply, feel free to re-open if you still feel this is an issue!
