### ISSUE TITLE
Scroll to Tab on Mobile with SetHash set to True

### ISSUE THREAD

**Issue by katart** [jellekralt/Responsive-Tabs#81]
I think it would be a good idea to add in a default option where the page would scroll to the active Tab on mobile device. 

If I open (or activate) a new accordion item that is below an already opened, long accordion item, the new active item will move up outside of the viewport. It would be nice to have the window scroll up with the accordion item.

Can this be done now with the tab-active callback? If so, can you explain how that can be done?

Thanks

**Comment by jellekralt** [comment]
This is actually an already existing option! You can enable the auto scrolling with the ```scrollToAccordion``` option: https://github.com/jellekralt/Responsive-Tabs#scroll-to-accordion-panel

**Comment by katart** [comment]
That's great! I must have overlooked that option.
