### ISSUE TITLE
hi Dev Team 

### ISSUE THREAD

**Issue by mahendaraReddy** [jellekralt/Responsive-Tabs#83]
After loading the page it take some time to load the tabs why? 
 
 1st its showing simple tabs with Tab Names then after few seconds  loading tabs in chrome and firefox.

**Comment by jellekralt** [comment]
Hi there, could you be a bit more specific to what is actually happening? For me the tabs load instantly in all browsers.

**Comment by geezer78** [comment]
Hi There, i see what mahendaraReddy means, i have the same "issue". on initial loading of the page the "divs and other items are not styled yet. they only get there css class after the script starts.
on slower connections a page can take some time to load but you already see the original tabs. but unstyled.

i just tried a quick hack by adding the styles and extra divs (headings) upfront, but this created double heading divs.

**Comment by mahendaraReddy** [comment]
yes i agree with you "geezer78" same issue here.

**Comment by jellekralt** [comment]
Yes, this is unfortunately unavoidable if you load scripts after your content, same thing happens with (for instance) jQuery UI Tabs. You could solve this by hiding the tabs before load with a class and removing it after load. I am not planning on adding anything to the plugin to solve this.
