### ISSUE TITLE
Check/Return state on load

### ISSUE THREAD

**Issue by lewismcarey** [jellekralt/Responsive-Tabs#84]
It would be handy to know the current state of the tabs (accordion/tabs) on load. It only appears to be available on a state change.

Is this possible already, if not can it be added easily?

**Comment by lewismcarey** [comment]
I have tried using the public getState method using:

    $tabs.responsiveTabs('getState');

But this does not seem to work.

**Comment by jellekralt** [comment]
Hi, I checked and it turned out that public method returns didn't work correctly. I've fixed it and released a new version (v1.5.2) in which this should work:
```js
$tabs.responsiveTabs('getState');
```
