### ISSUE TITLE
Arrows

### ISSUE THREAD

**Issue by dan0124** [jellekralt/Responsive-Tabs#87]
Hi,

Is it possible to add arrows depending on whether a tab is open or not?  E.g. down arrow when open, side arrow when closed.  That would be really useful.

Thanks,
Dan

**Comment by jellekralt** [comment]
Hi, 

You could do this yourself by adding an arrow icon to the tab by putting it inside the 
```javascript
 <li><a href="#tab-1">Responsive Tab-1</a></li>
```
element, and style it based on the ```r-tabs-state-active``` class.
