### ISSUE TITLE
startCollapsed not working for me

### ISSUE THREAD

**Issue by JulieKuehl** [jellekralt/Responsive-Tabs#91]
I'm stumped as to why the startCollapsed option isn't working for me. I have this code in place:

```
			<script>
				jQuery(document).ready(function($) {
					$('#tabs').responsiveTabs({
						startCollapsed: 'accordion',
						collapsible: 'accordion',
						animation: 'slide',
					});
					$( "#tabs" ).tabs({
						event: "mouseover",
					});
//					$('#tabs').responsiveTabs('deactivate', 0);
				});
			</script>
```
but in accordion mode, the first tab continues to be open upon loading. As you can see, I tried deactivating the first tab, but of course that also affects the desktop display. The code in question is in use over at http://aacrop.bcomhosting.com/

Any suggestions?

**Comment by jellekralt** [comment]
AFAIK the startCollapsed should work with the settings you included. I tried to check your website but I cant find any tabs, do you have an example for me?

**Comment by JulieKuehl** [comment]
Apologies. I should have let you know that the code had been removed from the site. Clients, you know. :-/

Thank you for your attention though.
