### ISSUE TITLE
scrollToAccordion fires on page load instead of click

### ISSUE THREAD

**Issue by leptest** [jellekralt/Responsive-Tabs#92]
The **scrollToAccordion** option fires on page load instead of when it's clicked.

I'm not sure if this is expected behaviour but i can see it causing issues if there are multiple accordions on the page at load time.  How will it know which one to scroll to?

I can put together a codepen if you want, but it seems self explanatory.

Cheers,
Daniel

**Comment by jellekralt** [comment]
Hi,

This was indeed the case. I've added a new option to disable this case. I've intentionally left it enabled because it is used by some people as a feature, rather than a bug. If you get the latest version (v1.6.0) and set ```scrollToAccordionOnLoad: false``` this should be solved for you.

**Comment by leptest** [comment]
Great!

Thank you!
