### ISSUE TITLE
Can't get the absolute url to open a tab.

### ISSUE THREAD

**Issue by kstudiofx** [jellekralt/Responsive-Tabs#93]
I'm trying to get the hash links to open a tab but it doesn't always work.  when you click on the link:

http://kstudiofx.com/GILEAD/?page_id=51#1

it doesn't open the first tab.  but if you already loaded the page and change that 1 to a 2, it'll open the 2nd tab, then back to 1 and it'll open the 1st tab but nothing when i first click on the link itself or enter it in the browser window.  Not sure what the issue is for me. If you could help, I'd appreciate it.  thanks!

**Comment by jellekralt** [comment]
This is because you have set the ```startCollapsed: true,``` options, which causes the plugin to start collapsed. That conflicts with the opening of the tab :). I don't know yet if its wise to change this feature so that it doesn't start collapsed when an absolute url is used..

**Comment by kstudiofx** [comment]
Awesome thank you so much!

On Mon, Feb 15, 2016 at 2:11 PM, Jelle Kralt <notifications@github.com>
wrote:

> This is because you have set the startCollapsed: true, options, which
> causes the plugin to start collapsed. That conflicts with the opening of
> the tab :). I don't know yet if its wise to change this feature so that it
> doesn't start collapsed when an absolute url is used..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jellekralt/Responsive-Tabs/issues/93#issuecomment-184350505>
> .
>



-- 
=============================

*Carina Gomez*
kstudio@kstudiofx.com
www.KStudioFX.com <http://www.kstudiofx.com/>
347.450.5539
web design - wordpress sites - print design
https://www.behance.net/kstudioc03d
www.linkedin.com/in/kstudiofx
=============================

**Comment by jellekralt** [comment]
You're welcome :)
