### ISSUE TITLE
multiple tabs on one side

### ISSUE THREAD

**Issue by cayoumedia** [jellekralt/Responsive-Tabs#94]
Hello there,
you can display multiple tabs on a page?

example:<xmp>
<div id="tabs1">
  <ul>
  	<li><a href="#tab-1"></li>
  	<li><a href="#tab-2"></li>
  	<li><a href="#tab-3"></li>
  </ul>
  <div id="tab-1">1</div>
  <div id="tab-2">2</div>
  <div id="tab-3">3</div>  
</div>

<div id="tabs2">
  <ul>
  	<li><a href="#tab-4"></li>
  	<li><a href="#tab-5"></li>
  	<li><a href="#tab-6"></li>
  </ul>
  <div id="tab-4">4</div>
  <div id="tab-5">5</div>
  <div id="tab-6">6</div>  
</div>
</xmp>

**Comment by jellekralt** [comment]
Do you mean having multiple instances? In that case you can just reference them with a jQuery selector. Example:

```html
<div id="tabs1">...</div>
<div id="tabs2">...</div>
```

```javascript
$('#tabs1,#tabs2').responsiveTabs();
```

**Comment by cayoumedia** [comment]
yes thanks!

**Comment by jellekralt** [comment]
You're welcome!

Btw, you could of course also use
```html
<div class="tabs">...</div>
<div class="tabs">...</div>
```

```javascript
$('.tabs').responsiveTabs();
```

Which is a bit more scalable :)
