### ISSUE TITLE
Trigger Google Analytics Event

### ISSUE THREAD

**Issue by Dooza** [jellekralt/Responsive-Tabs#95]
Hi there,
I want to fire off a Google Analytics event when someone clicks a tab. Has anyone done this before? I think I need to use "activate", but not sure how to get the name of the tab. Any ideas?

Cheers,

Dooza

**Comment by Dooza** [comment]
Figured it out:

```
activate: function(event, tab) {
ga('send','event','Tab','Clicked',tab.selector);
}
```

The only issue is that it fires as soon as the page loads as well as when a tab is clicked. I would prefer it to fire on just tab clicks. Any ideas?

Dooza

**Comment by jellekralt** [comment]
To solve it in a simple way you could do:

```javascript
$(document).ready(function () {
    var activated = false;

    $('#tab').responsiveTabs({
        activate: function(e, tab) {
            if (activated) {
                // Do your stuff
            }

            activated = true;
        }
    });
}); 
```
