### ISSUE TITLE
Gmap is not rendered.

### ISSUE THREAD

**Issue by Judapriest** [jellekralt/Responsive-Tabs#97]
Hello,

I have found this issue about gmap : https://github.com/jellekralt/Responsive-Tabs/issues/68

I was wondering if a rework of the plugin could be considered ? 
- Add a CSS class to non-active tabs instead of active tab
- This class trigger a position absolute and top -10000px (for example)
- And active tabs would just have display block

I don't know if it's understable, if not, let me know. I will try to rewrite it (As english isn't my mother tongue ^^').

Does this idea is problematic for accordion ? Because this way you would have a plugin working for almost everything.

Regards.

**Comment by jellekralt** [comment]
Hi there,

Thanks for your suggestion! This might be a trick worth considering. However, I am going to have to investigate if there aren't some edge case issues with this solution. One thing I can think of is that if you do this, the browser will still think it is 'visible' and therefore the content will still be focusable, and therefore strange behaviour might occur when tabbing through content.

That being said, i'll do some investigating/thinking about this subject and get back to you later. If you have any additional info/idea's about this, let me know!

**Comment by jellekralt** [comment]
Closing this issue due to me not expecting this will ever get picked up. PR's always welcome ofcourse.
